# Generated by Django 4.1.1 on 2022-10-09 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('serve_people_num', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('recipe_intro', models.TextField()),
                ('prep_time', models.IntegerField(default=0.5)),
                ('recipe_ingredients', models.TextField()),
                ('procedure', models.TextField()),
                ('video_tutorial', models.FileField(upload_to='')),
                ('note', models.TextField()),
                ('country_origin', models.CharField(max_length=20)),
                ('nutrition', models.TextField()),
                ('author', models.ManyToManyField(to='API.author')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_chiba_staff', models.BooleanField(default=False)),
                ('section', models.CharField(default='General', max_length=15)),
                ('description', models.TextField(default='General')),
                ('phone', models.CharField(max_length=15)),
                ('is_curator', models.BooleanField(default=False)),
                ('is_author', models.BooleanField(default=False)),
                ('is_chef', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField()),
                ('note', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
