# Generated by Django 4.1.1 on 2022-10-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='serve_time',
            field=models.CharField(choices=[('bf', 'Breakfast'), ('l', 'Lunch'), ('s', 'Supper'), ('a', 'Any Time')], default='a', max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_layout',
            field=models.TextField(choices=[('a', 'APPETIZER'), ('m', 'MAIN'), ('d', 'DESSERT')], default='m', max_length=10),
        ),
    ]
