# Generated by Django 4.1.1 on 2022-10-09 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='images',
            new_name='main_image',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='images',
            new_name='main_image',
        ),
    ]
