# Generated by Django 4.1.1 on 2022-10-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_meals_serve_time_recipe_recipe_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='recipes',
            field=models.ManyToManyField(to='API.recipe'),
        ),
    ]
