# Generated by Django 4.1.1 on 2022-10-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_rename_images_meal_main_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealreviews',
            name='alid_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mealreviews',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recipereviews',
            name='valid_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipereviews',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='main_image',
            field=models.FileField(blank=True, null=True, upload_to='media/videos'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/videos'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='main_image',
            field=models.FileField(blank=True, null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='video_tutorial',
            field=models.FileField(blank=True, null=True, upload_to='media/videos'),
        ),
        migrations.AlterField(
            model_name='recipereviews',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
