# Generated by Django 4.1.2 on 2022-10-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_mealreviews_alid_review_mealreviews_visible_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealreviews',
            old_name='alid_review',
            new_name='valid_review',
        ),
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default=4, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='slug',
            field=models.SlugField(default=3, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealreviews',
            name='slug',
            field=models.SlugField(default=3, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default=3, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipereviews',
            name='slug',
            field=models.SlugField(default=13, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='slug',
            field=models.SlugField(default=3, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='main_image',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='main_image',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='video_tutorial',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
